# Generated by Django 2.0.6 on 2018-10-24 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aktiviti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tajuk', models.CharField(max_length=300, verbose_name='Tajuk')),
                ('tempat', models.CharField(blank=True, max_length=300, null=True, verbose_name='Tempat')),
                ('penceramah', models.CharField(blank=True, max_length=300, null=True, verbose_name='Penceramah')),
                ('hadpeserta', models.IntegerField(blank=True, max_length=300, null=True, verbose_name='Had Perta')),
            ],
        ),
    ]
