# Generated by Django 2.0.6 on 2018-10-24 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penganjur', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aktiviti',
            name='hadpeserta',
            field=models.IntegerField(blank=True, null=True, verbose_name='Had Perta'),
        ),
    ]
